apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
  namespace: healthcare
data:
  PORT: "5003"
  DOCTOR_SERVICE_URL: "http://doctor-management-service:5002"
---
apiVersion: v1
kind: Secret
metadata:
  name: appointment-service-secret
  namespace: healthcare
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-appointment:27017/appointment_db"
  JWT_SECRET: "supersecretkey"
