services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: ${MONGO_URI_ATLAS}
      JWT_SECRET: ${JWT_SECRET} 
      PATIENT_SERVICE_URL: http://patient-service:5001
      NOTIFICATION_SERVICE_URL: http://notification-service:5002/api/notifications

  patient-service:
    build: ./services/patient-service
    container_name: patient-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: ${MONGO_URI_ATLAS}

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}

  doctor-service:
    build: ./services/doctor-management-service
    container_name: doctor-service
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
      MONGO_URI: ${MONGO_URI_ATLAS}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_URL: http://auth-service:5000

  appointment-service:
    build: ./services/appointment-service
    container_name: appointment-service
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      MONGO_URI: ${MONGO_URI_ATLAS}
      JWT_SECRET: ${JWT_SECRET}
      DOCTOR_SERVICE_URL: http://doctor-service:5004
      PATIENT_SERVICE_URL: http://patient-service:5001
      NOTIFICATION_SERVICE_URL: http://notification-service:5002/api/notifications

  telemedicine-service:
    build: ./services/telemedicine-service
    container_name: telemedicine-service
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      MONGO_URI: ${MONGO_URI_ATLAS}

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "8083:8083"
    environment:
      MONGO_URI: ${MONGO_URI_ATLAS}
      JWT_SECRET: ${JWT_SECRET}
      PAYHERE_MERCHANT_ID: ${PAYHERE_MERCHANT_ID}
      PAYHERE_MERCHANT_SECRET: ${PAYHERE_MERCHANT_SECRET}
      NOTIFY_URL: ${NOTIFY_URL}
      APPOINTMENT_SERVICE_URL: http://appointment-service:5005
      PATIENT_SERVICE_URL: http://patient-service:5001

  ai-symptom-checker:
    build: ./services/ai-symptom-service
    container_name: ai-symptom-service
    ports:
      - "8084:8084"
    environment:
      MONGO_URI: ${MONGO_URI_ATLAS}
      JWT_SECRET: ${JWT_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
