server.port=8083
spring.application.name=payment-service
security.jwt.secret=${JWT_SECRET}
spring.mongodb.uri=${MONGO_URI}
external.pay-here.merchant-id=${PAYHERE_MERCHANT_ID}
external.pay-here.merchant-secret=${PAYHERE_MERCHANT_SECRET}
external.pay-here.notify-url=${NOTIFY_URL}
external.pay-here.return-url=http://localhost:5173/patient/payment/result
external.pay-here.cancel-url=http://localhost:5173/patient/payment/result
external.appointment-service.base-url=${APPOINTMENT_SERVICE_URL}
external.patient-service.base-url=${PATIENT_SERVICE_URL}