server.port=8083
spring.application.name=payment-service
#TODO: Replace with actual value
security.jwt.secret=${JWT_SECRET}
spring.mongodb.uri=${MONGO_URI}
external.pay-here.merchant-id=${PAYHERE}
external.pay-here.merchant-secret=${MERCH_SECRET}
#TODO: Replace with actual values
external.pay-here.notify-url=${NOTIFY_URL}
#external.pay-here.return-url=http://localhost:3000/payment/success
#external.pay-here.cancel-url=http://localhost:3000/payment/cancel
external.pay-here.return-url=http://localhost:5173/patient/payment/result
external.pay-here.cancel-url=http://localhost:5173/patient/payment/result
#TODO: Replace with actual values
external.appointment-service.base-url=http://localhost:5003
external.patient-service.base-url=http://localhost:5001