spring.application.name=payment-service
#TODO: Replace with actual value
security.jwt.secret=mySecretKeyForPaymentServiceThatIsLongEnough123!
spring.mongodb.uri=mongodb+srv://thashmilajayasinghe_db_user:sFbBzgxIy5jLaWTv@cluster0.pxcvdco.mongodb.net/smart-healthcare-platform?appName=Cluster0
external.pay-here.merchant-id=1235153
external.pay-here.merchant-secret=NDU5MTk1NTU2MTQwOTgwNTUzMjQzNjY4NDczMDEzOTcwMDUwMg==
#TODO: Replace with actual values
external.pay-here.notify-url=https://chomp-equator-expel.ngrok-free.dev/api/payments/callback
#external.pay-here.return-url=http://localhost:3000/payment/success
#external.pay-here.cancel-url=http://localhost:3000/payment/cancel
#TODO: Replace with actual values
external.appointment-service.base-url=http://localhost:5003
