apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-service-config
  namespace: healthcare
data:
  PORT: "5002"
  AUTH_SERVICE_URL: "http://auth-service:5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: doctor-service-secret
  namespace: healthcare
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-doctor:27017/doctor_db"
  JWT_SECRET: "supersecretkey"
